//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veresiye
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariHesap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CariHesap()
        {
            this.CariHareket = new HashSet<CariHareket>();
        }
    
        public int Id { get; set; }
        public string CariKodu { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Unvan { get; set; }
        public string Yetkili { get; set; }
        public string Gsm { get; set; }
        public string Telefon { get; set; }
        public string Faks { get; set; }
        public string Adres { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string Eposta { get; set; }
        public string CariLimit { get; set; }
        public Nullable<bool> Hesap { get; set; }
        public string Kasa { get; set; }
        public Nullable<bool> Tur { get; set; }
        public string Alacak { get; set; }
        public string Borc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CariHareket> CariHareket { get; set; }
    }
}
