//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veresiye
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariHareket
    {
        public int Id { get; set; }
        public int CariId { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Tur { get; set; }
        public decimal Tutar { get; set; }
        public string Aciklama { get; set; }
    
        public virtual CariHesap CariHesap { get; set; }
    }
}
