//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veresiye
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string FirmaUnvani { get; set; }
        public string KullaniciAdi { get; set; }
        public string Parola { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string VergiNo { get; set; }
        public string VergiDairesi { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Eposta { get; set; }
    }
}
